name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        token: ${{ secrets.PAT }}
      - uses: education/autograding@v1
        id: autograder
      - run: >- curl -X PUT -H 'Content-type: application/json' -d '{"student username":"stuff","repo":"stuff","score":"stuff","outputs":"stuff"}' 'https://hooks.zapier.com/hooks/catch/912032/bsc6bg8/silent/'